title: "Bryce Larson"
description: "Personal portfolio and writing of Bryce Larson."

baseurl: ""
url: ""

markdown: kramdown

sass:
  sass_dir: css
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
